package com.example.clientapp.models

enum class Currency(val country: String, val currencyName: String, val currencyAcronym: String) {
    ALBANIA("Albania", "Albanian Lek", "ALL"),
    ANDORRA("Andorra", "Euro", "EUR"),
    AUSTRIA("Austria", "Euro", "EUR"),
    BELARUS("Belarus", "Belarus Ruble", "BYN"),
    BELGIUM("Belgium", "Euro", "EUR"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "Bosnia Mark", "BAM"),
    BULGARIA("Bulgaria", "Bulgaria Lev", "BGN"),
    CROATIA("Croatia", "Croatia Kuna", "HRK"),
    CZECH_REPUBLIC("Czech Republic", "Czech Koruna", "CZK"),
    DENMARK("Denmark", "Denmark Krone", "DKK"),
    ESTONIA("Estonia", "Euro", "EUR"),
    FINLAND("Finland", "Euro", "EUR"),
    FRANCE("France", "Euro", "EUR"),
    GERMANY("Germany", "Euro", "EUR"),
    GREECE("Greece", "Euro", "EUR"),
    HUNGARY("Hungary", "Hungary Forint", "HUF"),
    ICELAND("Iceland", "Iceland Krona", "ISK"),
    IRELAND("Ireland", "Euro", "EUR"),
    ITALY("Italy", "Euro", "EUR"),
    KOSOVO("Kosovo", "Euro", "EUR"),
    LATVIA("Latvia", "Euro", "EUR"),
    LIECHTENSTEIN("Liechtenstein", "Switzerland Franc", "CHF"),
    LITHUANIA("Lithuania", "Euro", "EUR"),
    LUXEMBOURG("Luxembourg", "Euro", "EUR"),
    MALTA("Malta", "Euro", "EUR"),
    MOLDOVA("Moldova", "Moldova Leu", "MDL"),
    MONACO("Monaco", "Euro", "EUR"),
    MONTENEGRO("Montenegro", "Euro", "EUR"),
    NETHERLANDS("Netherlands", "Euro", "EUR"),
    NORTH_MACEDONIA("North Macedonia", "Macedonia Denar", "MKD"),
    NORWAY("Norway", "Norway Kroner", "NOK"),
    POLAND("Poland", "Poland Zloty", "PLN"),
    PORTUGAL("Portugal", "Euro", "EUR"),
    ROMANIA("Romania", "Romania New Lei", "RON"),
    SAN_MARINO("San Marino", "Euro", "EUR"),
    SERBIA("Serbia", "Serbia Dinar", "RSD"),
    SLOVAKIA("Slovakia", "Euro", "EUR"),
    SLOVENIA("Slovenia", "Euro", "EUR"),
    SPAIN("Spain", "Euro", "EUR"),
    SWEDEN("Sweden", "Sweden Krona", "SEK"),
    SWITZERLAND("Switzerland", "Switzerland Franc", "CHF"),
    UKRAINE("Ukraine", "Ukraine Hryvnia", "UAH"),
    UNITED_KINGDOM("United Kingdom (UK)", "Pound Sterling", "GBP"),
    VATICAN_CITY("Vatican City (Holy See)", "Euro", "EUR"),
    ANGOLA("Angola", "Angolan Kwanza", "AOA"),
    BENIN("Benin", "West African CFA Franc", "XOF"),
    BOTSWANA("Botswana", "Botswana Pula", "BWP"),
    BURKINA_FASO("Burkina Faso", "West African CFA Franc", "XOF"),
    BURUNDI("Burundi", "Burundi Franc", "BIF"),
    CAMEROON("Cameroon", "Central African CFA Franc", "XAF"),
    CAPE_VERDE("Cape Verde", "Cape Verdean Escudo", "CVE"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "Central African CFA Franc", "XAF"),
    CHAD("Chad", "Central African CFA Franc", "XAF"),
    COMOROS("Comoros", "Comorian Franc", "KMF"),
    REPUBLIC_OF_THE_CONGO("Republic of the Congo", "Central African CFA Franc", "XAF"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Democratic Republic of the Congo", "Congolese Franc", "CDF"),
    DJIBOUTI("Djibouti", "Djiboutian Franc", "DJF"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "Central African CFA Franc", "XAF"),
    ERITREA("Eritrea", "Eritrean Nakfa", "ERN"),
    ESWATINI("Eswatini", "Lilangeni", "SZL"),
    ETHIOPIA("Ethiopia", "Ethiopian Birr", "ETB"),
    GABON("Gabon", "Central African CFA Franc", "XAF"),
    GAMBIA("Gambia", "Dalasi", "GMD"),
    GHANA("Ghana", "Ghanaian Cedi", "GHS"),
    GUINEA("Guinea", "Guinean Franc", "GNF"),
    GUINEA_BISSAU("Guinea-Bissau", "West African CFA Franc", "XOF"),
    IVORY_COAST("Ivory Coast", "West African CFA Franc", "XOF"),
    KENYA("Kenya", "Kenyan Shilling", "KES"),
    LESOTHO("Lesotho", "Lesotho Loti", "LSL"),
    LIBERIA("Liberia", "Liberian Dollar", "LRD"),
    LIBYA("Libya", "Libyan Dinar", "LYD"),
    MADAGASCAR("Madagascar", "Malagasy Ariary", "MGA"),
    MALAWI("Malawi", "Malawian Kwacha", "MWK"),
    MALI("Mali", "West African CFA Franc", "XOF"),
    MAURITANIA("Mauritania", "Ouguiya", "MRO"),
    MAURITIUS("Mauritius", "Mauritian Rupee", "MUR"),
    MOZAMBIQUE("Mozambique", "Mozambican Metical", "MZN"),
    NAMIBIA("Namibia", "Namibian Dollar", "NAD"),
    NIGER("Niger", "West African CFA Franc", "XOF"),
    NIGERIA("Nigeria", "Nigerian Naira", "NGN"),
    RWANDA("Rwanda", "Rwandan Franc", "RWF"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "São Tomé and Príncipe Dobra", "STD"),
    SENEGAL("Senegal", "West African CFA Franc", "XOF"),
    SEYCHELLES("Seychelles", "Seychellois Rupee", "SCR"),
    SIERRA_LEONE("Sierra Leone", "Sierra Leonean Leone", "SLL"),
    SOMALIA("Somalia", "Somali Shilling", "SOS"),
    SOUTH_AFRICA("South Africa", "South African Rand", "ZAR"),
    SOUTH_SUDAN("South Sudan", "South Sudanese Pound", "SSP"),
    TANZANIA("Tanzania", "Tanzanian Shilling", "TZS"),
    TOGO("Togo", "West African CFA Franc", "XOF"),
    UGANDA("Uganda", "Ugandan Shilling", "UGX"),
    ZAMBIA("Zambia", "Zambian Kwacha", "ZMW"),
    ZIMBABWE("Zimbabwe", "RTGS Dollar", "ZBN"),
    BANGLADESH("Bangladesh", "Taka", "BDT"),
    BHUTAN("Bhutan", "Bhutanese Ngultrum", "BTN"),
    BRUNEI("Brunei", "Brunei Dollar", "BND"),
    CAMBODIA("Cambodia", "Cambodian Riel", "KHR"),
    CHINA("China", "Renminbi (Yuan)", "CNY"),
    INDIA("India", "Indian Rupee", "INR"),
    INDONESIA("Indonesia", "Rupiah", "IDR"),
    JAPAN("Japan", "Yen", "JPY"),
    LAOS("Laos", "Lao Kip", "LAK"),
    MACAU("Macau", "Macanese Pataca", "MOP"),
    MALAYSIA("Malaysia", "Ringgit", "MYR"),
    MALDIVES("Maldives", "Maldivian Rufiyaa", "MVR"),
    MONGOLIA("Mongolia", "Mongolia Tögrög", "MNT"),
    MYANMAR("Myanmar", "Kyat", "MMK"),
    NEPAL("Nepal", "Nepalese Rupee", "NPR"),
    NORTH_KOREA("North Korea", "North Korean Won", "KPW"),
    PHILIPPINES("Philippines", "Philippine Peso", "PHP"),
    RUSSIA("Russia", "Russian Ruble", "RUB"),
    SINGAPORE("Singapore", "Singapore Dollar", "SGD"),
    SOUTH_KOREA("South Korea", "South Korean Won", "KRW"),
    SRI_LANKA("Sri Lanka", "Sri Lankan Rupee", "LKR"),
    TAIWAN("Taiwan", "New Taiwan Dollar", "TWD"),
    THAILAND("Thailand", "Baht", "THB"),
    TIMOR_LESTE("Timor-Leste", "US Dollar", "USD"),
    VIETNAM("Vietnam", "Vietnamese Dong", "VND"),
    AMERICAN_SAMOA("American Samoa", "US Dollar", "USD"),
    AUSTRALIA("Australia", "Australian Dollar", "AUD"),
    FEDERATED_STATES_OF_MICRONESIA("Federated States of Micronesia", "US Dollar", "USD"),
    FIJI("Fiji", "Fijian Dollar", "FJD"),
    COOK_ISLANDS("Cook Islands", "New Zealand Dollar", "NZD"),
    FRENCH_POLYNESIA("French Polynesia", "CFP Franc", "XPF"),
    GUAM("Guam", "US Dollar", "USD"),
    KIRIBATI("Kiribati", "Australian Dollar", "AUD"),
    MARSHALL_ISLANDS("Marshall Islands", "US Dollar", "USD"),
    NAURU("Nauru", "Australian Dollar", "AUD"),
    NEW_CALEDONIA("New Caledonia", "CFP Franc", "XPF"),
    NEW_ZEALAND("New Zealand", "New Zealand Dollar", "NZD"),
    NIUE("Niue", "New Zealand Dollar", "NZD"),
    NORFOLK_ISLAND("Norfolk Island", "Australian Dollar", "AUD"),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands", "US Dollar", "USD"),
    PALAU("Palau", "US Dollar", "USD"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "Papua New Guinean Kina", "PGK"),
    PITCAIRN_ISLANDS("Pitcairn Islands", "New Zealand Dollar", "NZD"),
    SAMOA("Samoa", "Samoan Tala", "WST"),
    SOLOMON_ISLANDS("Solomon Islands", "Solomon Islands Dollar", "SBD"),
    TOKELAU("Tokelau", "New Zealand Dollar", "NZD"),
    TONGA("Tonga", "Tongan Pa’anga", "TOP"),
    TUVALU("Tuvalu", "Australian Dollar", "AUD"),
    VANUATU("Vanuatu", "Vanuatu Vatu", "VUV"),
    WAKE_ISLAND("Wake Island", "US Dollar", "USD"),
    WALLIS_AND_FUTUNA("Wallis and Futuna", "CFP Franc", "XPF"),
    ALGERIA("Algeria", "Algerian Dinar", "DZD"),
    AFGHANISTAN("Afghanistan", "Afghan Afghani", "AFN"),
    ARMENIA("Armenia", "Armenian Dram", "AMD"),
    AZERBAIJAN("Azerbaijan", "Azerbaijani Manat", "AZN"),
    BAHRAIN("Bahrain", "Bahraini Dinar", "BHD"),
    CYPRUS("Cyprus", "Euro", "EUR"),
    EGYPT("Egypt", "Egyptian Pound", "EGP"),
    GEORGIA("Georgia", "Lari", "GEL"),
    IRAN("Iran", "Iranian Rial", "IRR"),
    IRAQ("Iraq", "Iraqi Dinar", "IQD"),
    ISRAEL("Israel", "Israeli New Shekel", "ILS"),
    JORDAN("Jordan", "Jordanian Dinar", "JOD"),
    KAZAKHSTAN("Kazakhstan", "Kazakhstani Tenge", "KZT"),
    KYRGYZSTAN("Kyrgyzstan", "Kyrgyzstani Som", "KGS"),
    KUWAIT("Kuwait", "Kuwaiti Dinar", "KWD"),
    LEBANON("Lebanon", "Lebanese Pound", "LBP"),
    MOROCCO("Morocco", "Moroccan Dirham", "MAD"),
    OMAN("Oman", "Omani Rial", "OMR"),
    PAKISTAN("Pakistan", "Pakistani Rupee", "PKR"),
    PALESTINE("Palestine", "Israeli New Shekel", "ILS"),
    QATAR("Qatar", "Qatari Riyal", "QAR"),
    SAUDI_ARABIA("Saudi Arabia", "Saudi Riyal", "SAR"),
    SYRIA("Syria", "Syrian Pound", "SYP"),
    TAJIKISTAN("Tajikistan", "Somoni", "TJS"),
    TUNISIA("Tunisia", "Tunisian Dinar", "TND"),
    TURKEY("Turkey", "Turkish Lira", "TRY"),
    TURKMENISTAN("Turkmenistan", "Turkmenistan Manat", "TMM"),
    UNITED_ARAB_EMIRATES("United Arab Emirates (UAE)", "UAE Dirham", "AED"),
    UZBEKISTAN("Uzbekistan", "Uzbekistan Som", "UZS"),
    YEMEN("Yemen", "Yemeni Rial", "YER"),
    BELIZE("Belize", "Belize Dollar", "BZD"),
    CANADA("Canada", "Canadian Dollar", "CAD"),
    COSTA_RICA("Costa Rica", "Costa Rican Colon", "CRC"),
    EL_SALVADOR("El Salvador", "US Dollar", "USD"),
    GREENLAND("Greenland", "Danish Krone", "DKK"),
    GUATEMALA("Guatemala", "Guatemalan Quetzal", "GTQ"),
    HONDURAS("Honduras", "Honduran Lempira", "HNL"),
    MEXICO("Mexico", "Mexican Peso", "MXB"),
    NICARAGUA("Nicaragua", "Nigerian Naira", "NGN"),
    PANAMA("Panama", "US Dollar", "USD"),
    SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon", "Euro", "EUR"),
    SINT_MAARTEN("Sint Maarten", "Netherlands Antillean Guilder", "ANG"),
    UNITED_STATES_OF_AMERICA("United States of America (USA)", "US Dollar", "USD"),
    ANGUILLA("Anguilla", "East Caribbean dollar", "XCD"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "East Caribbean dollar", "XCD"),
    ARUBA("Aruba", "Aruban Florin", "AWG"),
    BAHAMAS("Bahamas", "Bahamian dollar", "BSD"),
    BARBADOS("Barbados", "Barbadian dollar", "BBD"),
    BERMUDA("Bermuda", "Bermudian dollar", "BMD"),
    BRITISH_VIRGIN_ISLANDS("British Virgin Islands", "US dollar", "USD"),
    CAYMAN_ISLANDS("Cayman Islands", "Cayman Islands dollar", "KYD"),
    CUBA("Cuba", "Cuban peso", "CUP"),
    DOMINICA("Dominica", "East Caribbean dollar", "XCD"),
    DOMINICAN_REPUBLIC("Dominican Republic", "Dominican peso", "DOP"),
    GRENADA("Grenada", "East Caribbean dollar", "XCD"),
    GUADELOUPE("Guadeloupe", "Euro", "EUR"),
    HAITI("Haiti", "Haitian gourde", "HTG"),
    JAMAICA("Jamaica", "Jamaican dollar", "JMD"),
    MARTINIQUE("Martinique", "Euro", "EUR"),
    MONTSERRAT("Montserrat", "East Caribbean dollar", "XCD"),
    PUERTO_RICO("Puerto Rico", "US dollar", "USD"),
    SAINT_BARTHELEMY("Saint Barthelemy", "Euro", "EUR"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "East Caribbean dollar", "XCD"),
    SAINT_LUCIA("Saint Lucia", "East Caribbean dollar", "XCD"),
    SAINT_MARTIN("Saint Martin", "Euro", "EUR"),
    SAINT_VINCENT_AND_THE_GRENADINES(
        "Saint Vincent and the Grenadines",
        "East Caribbean dollar",
        "XCD"
    ),
    SINT_EUSTATIUS("Sint Eustatius", "US dollar", "USD"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "Trinidad and Tobago dollar", "TTD"),
    TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands", "US dollar", "USD"),
    US_VIRGIN_ISLANDS("US Virgin Islands", "US dollar", "USD"),
    ARGENTINA("Argentina", "Argentine peso", "ARS"),
    BOLIVIA("Bolivia", "Bolivian boliviano", "BOB"),
    BONAIRE("Bonaire", "US dollar", "USD"),
    BRAZIL("Brazil", "Brazilian real", "BRL"),
    CHILE("Chile", "Chilean peso", "CLP"),
    COLOMBIA("Colombia", "Colombian peso", "COP"),
    CURACAO("Curacao", "Netherlands Antillean guilder", "ANG"),
    ECUADOR("Ecuador", "US dollar", "USD"),
    FALKLAND_ISLANDS("Falkland Islands", "Falkland Islands pound", "FKP"),
    FRENCH_GUIANA("French Guiana", "Euro", "EUR"),
    GUYANA("Guyana", "Guyanese dollar", "GYD"),
    PARAGUAY("Paraguay", "Paraguayan guarani", "PYG"),
    PERU("Peru", "Peruvian sol", "PEN"),
    SABA("Saba", "US dollar", "USD"),
    SURINAME("Suriname", "Surinamese dollar", "SRD"),
    URUGUAY("Uruguay", "Uruguayan peso", "UYU"),
    VENEZUELA("Venezuela", "Venezuelan bolivar", "VES"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS(
        "South Georgia and the South Sandwich Islands",
        "Pound sterling",
        "GBP"
    ),
    
}